services:
  db:
    image: mariadb:10.11
    container_name: moodle-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  moodle:
    image: akj94/moodle-app:latest
    container_name: moodle-app
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./config.php:/var/www/html/config.php
      - moodledata:/var/www/moodledata
      - ./moodle.ini:/usr/local/etc/php/conf.d/moodle.ini
    restart: unless-stopped
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASS: moodlepassword

volumes:
  db_data:
  moodledata:

